export const singleFood = {
  discontinuedDate: "",
  foodComponents: [],
  foodAttributes: [
    {
      id: 2077783,
      value: 9,
      name: "Added Package Weight",
    },
  ],
  foodPortions: [],
  fdcId: 1935906,
  description: "BROCCOLI",
  publicationDate: "7/29/2021",
  foodNutrients: [
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1104,
        number: "318",
        name: "Vitamin A, IU",
        rank: 7500,
        unitName: "IU",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351165,
      amount: 2941.0,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1004,
        number: "204",
        name: "Total lipid (fat)",
        rank: 800,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351157,
      amount: 0e-8,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1003,
        number: "203",
        name: "Protein",
        rank: 600,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351156,
      amount: 3.53,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1005,
        number: "205",
        name: "Carbohydrate, by difference",
        rank: 1110,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351158,
      amount: 4.71,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1008,
        number: "208",
        name: "Energy",
        rank: 300,
        unitName: "kcal",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351159,
      amount: 29.0,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1258,
        number: "606",
        name: "Fatty acids, total saturated",
        rank: 9700,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351169,
      amount: 0e-8,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1089,
        number: "303",
        name: "Iron, Fe",
        rank: 5400,
        unitName: "mg",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351163,
      amount: 0.85,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1079,
        number: "291",
        name: "Fiber, total dietary",
        rank: 1200,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351161,
      amount: 3.5,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1093,
        number: "307",
        name: "Sodium, Na",
        rank: 5800,
        unitName: "mg",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351164,
      amount: 29.0,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1087,
        number: "301",
        name: "Calcium, Ca",
        rank: 5300,
        unitName: "mg",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351162,
      amount: 47.0,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1253,
        number: "601",
        name: "Cholesterol",
        rank: 15700,
        unitName: "mg",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351167,
      amount: 0e-8,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 2000,
        number: "269",
        name: "Sugars, total including NLEA",
        rank: 1510,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351160,
      amount: 2.35,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1257,
        number: "605",
        name: "Fatty acids, total trans",
        rank: 15400,
        unitName: "g",
      },
      foodNutrientDerivation: {
        id: 70,
        code: "LCCS",
        description: "Calculated from value per serving size measure",
      },
      id: 23351168,
      amount: 0e-8,
    },
    {
      type: "FoodNutrient",
      nutrient: {
        id: 1162,
        number: "401",
        name: "Vitamin C, total ascorbic acid",
        rank: 6300,
        unitName: "mg",
      },
      foodNutrientDerivation: {
        id: 75,
        code: "LCCD",
        description:
          "Calculated from a daily value percentage per serving size measure",
      },
      id: 23351166,
      amount: 91.8,
    },
  ],
  dataType: "Branded",
  foodClass: "Branded",
  modifiedDate: "3/13/2021",
  availableDate: "3/13/2021",
  brandOwner: "Curation Foods, Inc.",
  brandName: "EAT SMART",
  subbrandName: "BENEFORT'E",
  dataSource: "LI",
  brandedFoodCategory: "Pre-Packaged Fruit & Vegetables",
  gtinUpc: "709351891335",
  ingredients: "BROCCOLI",
  marketCountry: "United States",
  servingSize: 85.0,
  servingSizeUnit: "g",
  packageWeight: "32 oz/2 lbs/907 g",
  foodUpdateLog: [
    {
      discontinuedDate: "",
      foodAttributes: [],
      fdcId: 1935906,
      description: "BROCCOLI",
      publicationDate: "7/29/2021",
      dataType: "Branded",
      foodClass: "Branded",
      modifiedDate: "3/13/2021",
      availableDate: "3/13/2021",
      brandOwner: "Curation Foods, Inc.",
      brandName: "EAT SMART",
      subbrandName: "BENEFORT'E",
      dataSource: "LI",
      brandedFoodCategory: "Pre-Packaged Fruit & Vegetables",
      gtinUpc: "709351891335",
      ingredients: "BROCCOLI",
      marketCountry: "United States",
      servingSize: 85.0,
      servingSizeUnit: "g",
      packageWeight: "32 oz/2 lbs/907 g",
    },
    {
      discontinuedDate: "",
      foodAttributes: [],
      fdcId: 1804280,
      description: "BROCCOLI",
      publicationDate: "6/17/2021",
      dataType: "Branded",
      foodClass: "Branded",
      modifiedDate: "3/13/2021",
      availableDate: "3/13/2021",
      brandOwner: "Curation Foods, Inc.",
      brandName: "EAT SMART",
      subbrandName: "BENEFORT'E",
      dataSource: "LI",
      brandedFoodCategory: "Pre-Packaged Fruit & Vegetables",
      gtinUpc: "709351891335",
      ingredients: "BROCCOLI",
      marketCountry: "United States",
      servingSize: 85.0,
      servingSizeUnit: "g",
      packageWeight: "907 g",
    },
  ],
  labelNutrients: {
    fat: {
      value: 0.0,
    },
    saturatedFat: {
      value: 0.0,
    },
    transFat: {
      value: 0.0,
    },
    cholesterol: {
      value: 0.0,
    },
    sodium: {
      value: 24.6,
    },
    carbohydrates: {
      value: 4.0,
    },
    fiber: {
      value: 2.98,
    },
    sugars: {
      value: 2.0,
    },
    protein: {
      value: 3.0,
    },
    calcium: {
      value: 40.0,
    },
    iron: {
      value: 0.722,
    },
    calories: {
      value: 24.6,
    },
  },
};
