import { FoodSearchJson } from "./types/FoodDataTypes";

export const useFakeData = false;
export const fakeSearch: FoodSearchJson = {
  foods: [
    {
      description: "Broccoli",
      fdcId: 1935906,
      dataType: "",
      brandName: "BRAND",
      brandOwner: "OWNER",
      foodCategory: "",
      servingSize: 12,
      servingSizeUnit: "g",
      foodNutrients: [
        {
          fdcName: "Fat",
          displayName: "Fat",
          amount: 2,
          unit: "g",
          dailyValue: 13,
          isMajorNutrient: true,
        },
        {
          fdcName: "Carbohydrates",
          displayName: "",
          isMajorNutrient: true,
          amount: 7,
          unit: "g",
          dailyValue: 8,
        },
        {
          fdcName: "Vitamin C",
          displayName: "",
          isMajorNutrient: false,
          amount: 14,
          unit: "mg",
          dailyValue: 32,
        },
      ],
    },
    {
      description: "Cucumber",
      fdcId: 111111,
      dataType: "",
      brandName: "BRAND",
      brandOwner: "OWNER",
      foodCategory: "",
      servingSize: 12,
      servingSizeUnit: "g",
      foodNutrients: [
        {
          fdcName: "Fat",
          displayName: "",
          isMajorNutrient: true,
          amount: 2,
          unit: "g",
          dailyValue: 13,
        },
        {
          fdcName: "Carbohydrates",
          displayName: "",
          isMajorNutrient: true,
          amount: 7,
          unit: "g",
          dailyValue: 8,
        },
        {
          fdcName: "Vitamin C",
          displayName: "",
          isMajorNutrient: false,
          amount: 14,
          unit: "mg",
          dailyValue: 32,
        },
      ],
    },
    {
      description: "Tomato",
      fdcId: 23874,
      dataType: "",
      brandName: "BRAND",
      brandOwner: "OWNER",
      foodCategory: "",
      servingSize: 12,
      servingSizeUnit: "g",
      foodNutrients: [
        {
          fdcName: "Fat",
          displayName: "",
          isMajorNutrient: true,
          amount: 2,
          unit: "g",
          dailyValue: 13,
        },
        {
          fdcName: "Carbohydrates",
          displayName: "",
          isMajorNutrient: true,
          amount: 7,
          unit: "g",
          dailyValue: 8,
        },
        {
          fdcName: "Vitamin C",
          displayName: "",
          isMajorNutrient: false,
          amount: 14,
          unit: "mg",
          dailyValue: 32,
        },
      ],
    },
    {
      description: "Cookie",
      fdcId: 8977655,
      dataType: "",
      brandName: "BRAND",
      brandOwner: "OWNER",
      foodCategory: "",
      servingSize: 12,
      servingSizeUnit: "g",
      foodNutrients: [
        {
          fdcName: "Fat",
          displayName: "",
          isMajorNutrient: true,
          amount: 2,
          unit: "g",
          dailyValue: 13,
        },
        {
          fdcName: "Carbohydrates",
          displayName: "",
          isMajorNutrient: true,
          amount: 7,
          unit: "g",
          dailyValue: 8,
        },
        {
          fdcName: "Vitamin C",
          displayName: "",
          isMajorNutrient: false,
          amount: 14,
          unit: "mg",
          dailyValue: 32,
        },
      ],
    },
    {
      description: "Wheat Bread",
      fdcId: 879613,
      dataType: "",
      brandName: "BRAND",
      brandOwner: "OWNER",
      foodCategory: "",
      servingSize: 12,
      servingSizeUnit: "g",
      foodNutrients: [
        {
          fdcName: "Fat",
          displayName: "",
          isMajorNutrient: true,
          amount: 2,
          unit: "g",
          dailyValue: 13,
        },
        {
          fdcName: "Carbohydrates",
          displayName: "",
          isMajorNutrient: true,
          amount: 7,
          unit: "g",
          dailyValue: 8,
        },
        {
          fdcName: "Vitamin C",
          displayName: "",
          isMajorNutrient: false,
          amount: 14,
          unit: "mg",
          dailyValue: 32,
        },
      ],
    },
  ],
};

export const fakeSingleFoods = [
  {
    fdcId: 1935906,
    description: "Broccoli",
    foodNutrients: [
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1104,
          number: "318",
          name: "Vitamin A, IU",
          rank: 7500,
          unit: "IU",
        },
        id: 23351165,
        amount: 2941.0,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1004,
          number: "204",
          name: "Total lipid (fat)",
          rank: 800,
          unit: "g",
        },
        id: 23351157,
        amount: 0e-8,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1003,
          number: "203",
          name: "Protein",
          rank: 600,
          unit: "g",
        },
        id: 23351156,
        amount: 3.53,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1005,
          number: "205",
          name: "Carbohydrate, by difference",
          rank: 1110,
          unit: "g",
        },
        id: 23351158,
        amount: 4.71,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1008,
          number: "208",
          name: "Energy",
          rank: 300,
          unit: "kcal",
        },
        id: 23351159,
        amount: 29.0,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1258,
          number: "606",
          name: "Fatty acids, total saturated",
          rank: 9700,
          unit: "g",
        },
        id: 23351169,
        amount: 0e-8,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1089,
          number: "303",
          name: "Iron, Fe",
          rank: 5400,
          unit: "mg",
        },
        id: 23351163,
        amount: 0.85,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1079,
          number: "291",
          name: "Fiber, total dietary",
          rank: 1200,
          unit: "g",
        },
        id: 23351161,
        amount: 3.5,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1093,
          number: "307",
          name: "Sodium, Na",
          rank: 5800,
          unit: "mg",
        },
        id: 23351164,
        amount: 29.0,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1087,
          number: "301",
          name: "Calcium, Ca",
          rank: 5300,
          unit: "mg",
        },
        id: 23351162,
        amount: 47.0,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1253,
          number: "601",
          name: "Cholesterol",
          rank: 15700,
          unit: "mg",
        },
        id: 23351167,
        amount: 0e-8,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 2000,
          number: "269",
          name: "Sugars, total including NLEA",
          rank: 1510,
          unit: "g",
        },
        id: 23351160,
        amount: 2.35,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1257,
          number: "605",
          name: "Fatty acids, total trans",
          rank: 15400,
          unit: "g",
        },
        id: 23351168,
        amount: 0e-8,
      },
      {
        type: "FoodNutrient",
        nutrient: {
          id: 1162,
          number: "401",
          name: "Vitamin C, total ascorbic acid",
          rank: 6300,
          unit: "mg",
        },
        id: 23351166,
        amount: 91.8,
      },
    ],
    dataType: "Branded",
    brandOwner: "Curation Foods, Inc.",
    brandName: "EAT SMART",
    subbrandName: "BENEFORT'E",
    brandedFoodCategory: "Pre-Packaged Fruit & Vegetables",
    ingredients: "BROCCOLI",
    marketCountry: "United States",
    servingSize: 85.0,
    servingSizeUnit: "g",
    labelNutrients: {
      fat: {
        value: 0.0,
      },
      saturatedFat: {
        value: 0.0,
      },
      transFat: {
        value: 0.0,
      },
      cholesterol: {
        value: 0.0,
      },
      sodium: {
        value: 24.6,
      },
      carbohydrates: {
        value: 4.0,
      },
      fiber: {
        value: 2.98,
      },
      sugars: {
        value: 2.0,
      },
      protein: {
        value: 3.0,
      },
      calcium: {
        value: 40.0,
      },
      iron: {
        value: 0.722,
      },
      calories: {
        value: 24.6,
      },
    },
  },
];
